export const HawkConfig = {
  PUSH_TO_ADDR: 'push_to_addr',
  PUSH_TO_PORT: 'push_to_port',

  API_URL: 'api_url',
  API_HISTORY: 'api_history',
  LIVE_URL: 'live_url',
  LIVE_HISTORY: 'live_history',
  EPG_URL: 'epg_url',
  EPG_HISTORY: 'epg_history',
  PROXY_SERVER: 'proxy_server',

  DEBUG_OPEN: 'debug_open',
  HOME_API: 'home_api',
  HOME_REC: 'home_rec',
  HOME_REC_STYLE: 'home_rec_style',
  HOME_NUM: 'home_num',
  HOME_SHOW_SOURCE: 'show_source',
  HOME_LOCALE: 'language',
  HOME_SEARCH_POSITION: 'search_position',
  HOME_MENU_POSITION: 'menu_position',
  HOME_DEFAULT_SHOW: 'home_default_show',

  SHOW_PREVIEW: 'show_preview',
  IJK_CODEC: 'ijk_codec',
  PLAY_TYPE: 'play_type',
  PLAY_RENDER: 'play_render',
  PLAY_SCALE: 'play_scale',
  PLAY_TIME_STEP: 'play_time_step',
  PIC_IN_PIC: 'pic_in_pic',
  VIDEO_PURIFY: 'video_purify',
  IJK_CACHE_PLAY: 'ijk_cache_play',
  EXO_RENDERER: 'exo_renderer',
  EXO_RENDERER_MODE: 'exo_renderer_mode',
  VOD_PLAYER_PREFERRED: 'vod_player_preferred',

  DOH_URL: 'doh_url',
  DEFAULT_PARSE: 'parse_default',
  PARSE_WEBVIEW: 'parse_webview',
  SEARCH_VIEW: 'search_view',
  SOURCES_FOR_SEARCH: 'checked_sources_for_search',
  STORAGE_DRIVE_SORT: 'storage_drive_sort',
  SUBTITLE_TEXT_SIZE: 'subtitle_text_size',
  SUBTITLE_TEXT_STYLE: 'subtitle_text_style',
  SUBTITLE_TIME_DELAY: 'subtitle_time_delay',
  DANMU_OPEN: 'danmu_open',
  DANMU_MAXLINE: 'danmu_maxline',
  DANMU_SPEED: 'danmu_speed',
  DANMU_ALPHA: 'danmu_alpha',
  DANMU_SIZESCALE: 'danmu_sizescale',
  DANMU_COLOR: 'danmu_color',
  THEME_SELECT: 'theme_select',
  BACKGROUND_PLAY_TYPE: 'background_play_type',
  FAST_SEARCH_MODE: 'fast_search_mode',
  SCREEN_DISPLAY: 'screen_display',
  SEARCH_FILTER_KEY: 'search_filter_key',

  LIVE_CHANNEL: 'last_live_channel_name',
  LIVE_CHANNEL_GROUP: 'last_live_channel_group_name',
  LIVE_CHANNEL_REVERSE: 'live_channel_reverse',
  LIVE_CROSS_GROUP: 'live_cross_group',
  LIVE_CONNECT_TIMEOUT: 'live_connect_timeout',
  LIVE_SHOW_NET_SPEED: 'live_show_net_speed',
  LIVE_SHOW_TIME: 'live_show_time',
  LIVE_SKIP_PASSWORD: 'live_skip_password',
  LIVE_PLAYER_TYPE: 'live_player_type'
} as const;

export type HawkConfigKey = typeof HawkConfig[keyof typeof HawkConfig];
